### ISSUE TITLE
Off-canvas menu defaults not set properly

### ISSUE THREAD

**Issue by ethanmay** [olefredrik/FoundationPress#447]
When using the WP menu editor to set a menu to the "Mobile" theme location, the off-canvas menu will not display until you go through the following process:
 1. Open Customizer > "Mobile Menu Settings"
 2. Open "Mobile navigaton layout"
 3. Default is set to off-canvas, select topbar then off-canvas in order to re-save the menu
  - Note: if you save and leave the customizer at this point, the front end will display the off-canvas menu but it will be broken.
 4. Go back, open "Mobile navigation position"
 5. Default is set to left, select right then left in order to re-save the menu
 6. Off-canvas menu now displays as expected

Tested in WP 4.3 using FoundationPress 1.2.0.

PS - Love Zurb, love FoundationPress, thanks for this awesome resource. :+1:

**Comment by olefredrik** [comment]
Thanks for your bug report and quickfix :+1:

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/449

**Comment by chriscarpenter12** [comment]
I still had this issue still after the merge. I had to do exactly as @ethanmay described to get the offcanvas to work correctly. I verified I had the changes in #449.

**Comment by jochienabuurs** [comment]
Issue still exists indeed. I pulled in the code just a few hours ago so i'm sure i have the newest version.

**Comment by adibbz** [comment]
Still seeing this issue today. Pulled code this past monday.

**Comment by olefredrik** [comment]
Hi guys. @skoldin has made a bugfix: https://github.com/olefredrik/FoundationPress/pull/471
Please pull the latest version and verify that everything is working as expected.
